CREATE TABLE mytable(
   Tittle VARCHAR(39) NOT NULL PRIMARY KEY
  ,Rating NUMERIC(4,1)
);
INSERT INTO mytable(Tittle,Rating) VALUES ('Good Newwz',3.4);
INSERT INTO mytable(Tittle,Rating) VALUES ('Dabangg 3',3.2);
INSERT INTO mytable(Tittle,Rating) VALUES ('Sound Of Water',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('The Body',2.8);
INSERT INTO mytable(Tittle,Rating) VALUES ('Mudda 370 J&K',1.7);
INSERT INTO mytable(Tittle,Rating) VALUES ('Kanoon Ke Khiladi',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Unfriends',1.7);
INSERT INTO mytable(Tittle,Rating) VALUES ('Mardaani 2',3.4);
INSERT INTO mytable(Tittle,Rating) VALUES ('Panipat',3.3);
INSERT INTO mytable(Tittle,Rating) VALUES ('A Gift Of Love: Sifar',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Pati Patni Aur Woh',3.4);
INSERT INTO mytable(Tittle,Rating) VALUES ('X Ray: The Inner Image',2.6);
INSERT INTO mytable(Tittle,Rating) VALUES ('LuvUTurn',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Tony',2.8);
INSERT INTO mytable(Tittle,Rating) VALUES ('Yeh Saali Aashiqui',3.2);
INSERT INTO mytable(Tittle,Rating) VALUES ('Commando 3',2.9);
INSERT INTO mytable(Tittle,Rating) VALUES ('Dosti Zindabad',1.8);
INSERT INTO mytable(Tittle,Rating) VALUES ('Pagalpanti',2.5);
INSERT INTO mytable(Tittle,Rating) VALUES ('Lafange Nawab',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Romi The Hero',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Motichoor Chaknachoor',2.9);
INSERT INTO mytable(Tittle,Rating) VALUES ('Keep Safe Distance',1.7);
INSERT INTO mytable(Tittle,Rating) VALUES ('Marrne Bhi Do Yaaron',2.5);
INSERT INTO mytable(Tittle,Rating) VALUES ('Bagpat Ka Dulha',1.8);
INSERT INTO mytable(Tittle,Rating) VALUES ('Marjaavaan',2.8);
INSERT INTO mytable(Tittle,Rating) VALUES ('Jhalki',2.5);
INSERT INTO mytable(Tittle,Rating) VALUES ('Make In India',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Satellite Shankar',2.4);
INSERT INTO mytable(Tittle,Rating) VALUES ('Mr.Black Mr.White',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Bala',4.2);
INSERT INTO mytable(Tittle,Rating) VALUES ('Laughter Ke Chapter',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Bypass Road',2.5);
INSERT INTO mytable(Tittle,Rating) VALUES ('Ekta',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Ujda Chaman',3);
INSERT INTO mytable(Tittle,Rating) VALUES ('Zindagi Tumse',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Made In China',3.2);
INSERT INTO mytable(Tittle,Rating) VALUES ('Saand Ki Aankh',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Housefull 4',2.6);
INSERT INTO mytable(Tittle,Rating) VALUES ('Love in College',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('P Se Pyaar F Se Faraar',2.6);
INSERT INTO mytable(Tittle,Rating) VALUES ('Life Mein Time Nahi Hai Kisi Ko',2.2);
INSERT INTO mytable(Tittle,Rating) VALUES ('Love Shots',1.7);
INSERT INTO mytable(Tittle,Rating) VALUES ('#Yaaram',2.5);
INSERT INTO mytable(Tittle,Rating) VALUES ('Ghost',2.6);
INSERT INTO mytable(Tittle,Rating) VALUES ('Kirket',2.5);
INSERT INTO mytable(Tittle,Rating) VALUES ('Junction Varanasi',2.6);
INSERT INTO mytable(Tittle,Rating) VALUES ('Officer Arjun Singh IPS',2.3);
INSERT INTO mytable(Tittle,Rating) VALUES ('Laal Kaptaan',2.9);
INSERT INTO mytable(Tittle,Rating) VALUES ('Jo Hal Dil Ka',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Jacqueline I Am Coming',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('The Sky Is Pink',3.5);
INSERT INTO mytable(Tittle,Rating) VALUES ('The Destiny Samaj Of Banjaraa',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('War',3.4);
INSERT INTO mytable(Tittle,Rating) VALUES ('Little Baby',2.5);
INSERT INTO mytable(Tittle,Rating) VALUES ('Main Zaroor Aaunga',2.1);
INSERT INTO mytable(Tittle,Rating) VALUES ('Kandy Twist',2.2);
INSERT INTO mytable(Tittle,Rating) VALUES ('Pyaar Karle',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Hum To Huye Hain Tumhare',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Cypher: Shoonya Se Shikhar Tak',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Prassthanam',3.2);
INSERT INTO mytable(Tittle,Rating) VALUES ('Pal Pal Dil Ke Paas',2.9);
INSERT INTO mytable(Tittle,Rating) VALUES ('The Zoya Factor',3.3);
INSERT INTO mytable(Tittle,Rating) VALUES ('Section 375',4);
INSERT INTO mytable(Tittle,Rating) VALUES ('Dream Girl',3.5);
INSERT INTO mytable(Tittle,Rating) VALUES ('College ke Din Char',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Pehlwaan',3);
INSERT INTO mytable(Tittle,Rating) VALUES ('Chhichhore',3.6);
INSERT INTO mytable(Tittle,Rating) VALUES ('Fairr In Love',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Saaho',2.6);
INSERT INTO mytable(Tittle,Rating) VALUES ('Ammaa Ki Boli',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Ghode Ko Jalebi Khilane Le Ja Riya Hoon',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Mission Mangal',3.6);
INSERT INTO mytable(Tittle,Rating) VALUES ('Batla House',3.6);
INSERT INTO mytable(Tittle,Rating) VALUES ('Dangerous Killer',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Pranaam',2.4);
INSERT INTO mytable(Tittle,Rating) VALUES ('Jabariya Jodi',2.7);
INSERT INTO mytable(Tittle,Rating) VALUES ('Chicken Curry Law',2.1);
INSERT INTO mytable(Tittle,Rating) VALUES ('Mushkil',1.7);
INSERT INTO mytable(Tittle,Rating) VALUES ('Berozgaar Leader',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Khandaani Shafakhana',3.1);
INSERT INTO mytable(Tittle,Rating) VALUES ('Chase: No Mercy To Crime',2.2);
INSERT INTO mytable(Tittle,Rating) VALUES ('Moksh To Maya',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Judgementall Hai Kya',3.3);
INSERT INTO mytable(Tittle,Rating) VALUES ('Arjun Patiala',2.4);
INSERT INTO mytable(Tittle,Rating) VALUES ('Forty Plus',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Mohai Jungle',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Meri Bhagya Laxmi',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Hyderabad Nawabs 2',3.1);
INSERT INTO mytable(Tittle,Rating) VALUES ('Wig Boss',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Jhootha Kahin Ka',2.7);
INSERT INTO mytable(Tittle,Rating) VALUES ('Family Of Thakurganj',2.5);
INSERT INTO mytable(Tittle,Rating) VALUES ('Shaadi Ke Patasey',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Penalty',2.2);
INSERT INTO mytable(Tittle,Rating) VALUES ('Kanchani Aaj Bhi Hai',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Super 30',3.7);
INSERT INTO mytable(Tittle,Rating) VALUES ('Time To Retaliate: Masoom',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Malaal',3.2);
INSERT INTO mytable(Tittle,Rating) VALUES ('Marudhar Express',2.5);
INSERT INTO mytable(Tittle,Rating) VALUES ('Hume Tumse Pyaar Kitna',2.4);
INSERT INTO mytable(Tittle,Rating) VALUES ('One Day: Justice Delivered',2.8);
INSERT INTO mytable(Tittle,Rating) VALUES ('Article 15',4.3);
INSERT INTO mytable(Tittle,Rating) VALUES ('Bhajan Supari',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('The Great Indian Escape',2.8);
INSERT INTO mytable(Tittle,Rating) VALUES ('Fastey Fasaatey',2.1);
INSERT INTO mytable(Tittle,Rating) VALUES ('Code Blue',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Belagaam',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Kabir Singh',3.5);
INSERT INTO mytable(Tittle,Rating) VALUES ('Khel Khallas',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Rescue',1.3);
INSERT INTO mytable(Tittle,Rating) VALUES ('Kissebaaz',2.1);
INSERT INTO mytable(Tittle,Rating) VALUES ('Khamoshi',2.5);
INSERT INTO mytable(Tittle,Rating) VALUES ('Asli Fighter',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Bharat',3.3);
INSERT INTO mytable(Tittle,Rating) VALUES ('Nakkash',3);
INSERT INTO mytable(Tittle,Rating) VALUES ('Shuruaat Ka Twist',3.1);
INSERT INTO mytable(Tittle,Rating) VALUES ('Deva Ek Rakshak',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Naughty Gang',2);
INSERT INTO mytable(Tittle,Rating) VALUES ('Yeh Hai India',2.2);
INSERT INTO mytable(Tittle,Rating) VALUES ('PM Narendra Modi',2.6);
INSERT INTO mytable(Tittle,Rating) VALUES ('India''s Most Wanted',3.3);
INSERT INTO mytable(Tittle,Rating) VALUES ('On The Ramp Never Ending Show',2.4);
INSERT INTO mytable(Tittle,Rating) VALUES ('Chaturnath',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Kadke Kamal Ke',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Savdhan : Ek Adbhut Kahaani',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Gunwali Dulhaniya',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Chorriyan Chhoron Se Kam Nahi Hoti',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('De De Pyaar De',3.4);
INSERT INTO mytable(Tittle,Rating) VALUES ('Student Of The Year 2',3);
INSERT INTO mytable(Tittle,Rating) VALUES ('Never Give Up',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Grihalakshmi: The Awakening',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Inspector Vijay',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Chhal Kiya Kisne',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Chhota Bheem Kung Fu Dhamaka',3.3);
INSERT INTO mytable(Tittle,Rating) VALUES ('3rd Eye',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Setters',2.8);
INSERT INTO mytable(Tittle,Rating) VALUES ('Blank',2.9);
INSERT INTO mytable(Tittle,Rating) VALUES ('1978 A Teen Night Out',2.1);
INSERT INTO mytable(Tittle,Rating) VALUES ('Hansa Ek Sanyog',2.3);
INSERT INTO mytable(Tittle,Rating) VALUES ('Tarpan',1.7);
INSERT INTO mytable(Tittle,Rating) VALUES ('Kalank',3);
INSERT INTO mytable(Tittle,Rating) VALUES ('Maa Purnagiri',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Blackboard Vs Whiteboard',2.1);
INSERT INTO mytable(Tittle,Rating) VALUES ('Betiyon Ki Balle Balle',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Albert Pinto Ko Gussa Kyon Ata Hai',3.1);
INSERT INTO mytable(Tittle,Rating) VALUES ('The Tashkent Files',2.9);
INSERT INTO mytable(Tittle,Rating) VALUES ('Gun Pe Done',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Paharganj',2.1);
INSERT INTO mytable(Tittle,Rating) VALUES ('Ek Hakikat Ganga',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Chousar Firangi',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Romeo Akbar Walter',3.4);
INSERT INTO mytable(Tittle,Rating) VALUES ('Jai Chhathi Maa',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Railway Raju',2);
INSERT INTO mytable(Tittle,Rating) VALUES ('Gone Kesh',3.2);
INSERT INTO mytable(Tittle,Rating) VALUES ('Notebook',3.1);
INSERT INTO mytable(Tittle,Rating) VALUES ('Junglee',3.3);
INSERT INTO mytable(Tittle,Rating) VALUES ('Ram Ki Janmabhoomi',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Tennis Buddies',2.5);
INSERT INTO mytable(Tittle,Rating) VALUES ('Challenge',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Kesari',4.5);
INSERT INTO mytable(Tittle,Rating) VALUES ('Mard Ko Dard Nahi Hota',3.2);
INSERT INTO mytable(Tittle,Rating) VALUES ('The Pushkar Lodge',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Bindi',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Photograph',3.1);
INSERT INTO mytable(Tittle,Rating) VALUES ('Mere Pyare Prime Minister',3);
INSERT INTO mytable(Tittle,Rating) VALUES ('Milan Talkies',2.6);
INSERT INTO mytable(Tittle,Rating) VALUES ('Sharmaji Ki Lag Gai',2.6);
INSERT INTO mytable(Tittle,Rating) VALUES ('22 Yards',2.2);
INSERT INTO mytable(Tittle,Rating) VALUES ('Hamid',3.7);
INSERT INTO mytable(Tittle,Rating) VALUES ('Risknamaa',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Just Love: The God Particle',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Lul Bate Lul',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Is She Raju?',2.4);
INSERT INTO mytable(Tittle,Rating) VALUES ('Yeh Suhaagraat Impossible',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Suspense',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Phir Ussi Mod Par',2.5);
INSERT INTO mytable(Tittle,Rating) VALUES ('Badla',3.6);
INSERT INTO mytable(Tittle,Rating) VALUES ('God Of Gods',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Sonchiriya',3.2);
INSERT INTO mytable(Tittle,Rating) VALUES ('GGBB: Goopi Gawaiya Bagha Bajaiya',3.2);
INSERT INTO mytable(Tittle,Rating) VALUES ('Luka Chuppi',3.4);
INSERT INTO mytable(Tittle,Rating) VALUES ('Total Dhamaal',2.3);
INSERT INTO mytable(Tittle,Rating) VALUES ('Number Game',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Shudra A Love Story',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Operation Cobra',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Hum Chaar',2.8);
INSERT INTO mytable(Tittle,Rating) VALUES ('Facebook Wala Pyar',2.1);
INSERT INTO mytable(Tittle,Rating) VALUES ('Gully Boy',4.3);
INSERT INTO mytable(Tittle,Rating) VALUES ('Khandala Night',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('The Fakir Of Venice',2.6);
INSERT INTO mytable(Tittle,Rating) VALUES ('Amavas',2.1);
INSERT INTO mytable(Tittle,Rating) VALUES ('End Counter',2.1);
INSERT INTO mytable(Tittle,Rating) VALUES ('Naya Satya',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Jhol',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Parking Closed',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Dosti Ke Side Effectss',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('SP Chauhan: A Struggling Man',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Umakant Pandey Purush Ya ... ?',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Ek Ladki Ko Dekha Toh Aisa Laga',3.3);
INSERT INTO mytable(Tittle,Rating) VALUES ('Picture Ki Cheerphad `Papi Gudia''',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Mansukh Chaturvedi Ki Atmakatha',1.7);
INSERT INTO mytable(Tittle,Rating) VALUES ('Jaipur Junction',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Manikarnika: The Queen Of Jhansi',3.6);
INSERT INTO mytable(Tittle,Rating) VALUES ('Thackeray',3.1);
INSERT INTO mytable(Tittle,Rating) VALUES ('72 Hours: Martyr Who Never Died',2.6);
INSERT INTO mytable(Tittle,Rating) VALUES ('Bombairiya',2.5);
INSERT INTO mytable(Tittle,Rating) VALUES ('Chhappan Bhai',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Fraud Saiyaan',1.8);
INSERT INTO mytable(Tittle,Rating) VALUES ('Rangeela Raja',1.6);
INSERT INTO mytable(Tittle,Rating) VALUES ('Woh Jo Tha Ek Massiah Maulana Azad',2.7);
INSERT INTO mytable(Tittle,Rating) VALUES ('Little Boy',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('The Lift Boy',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Why Cheat India',3.1);
INSERT INTO mytable(Tittle,Rating) VALUES ('Pagal Kar Diya Toone',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Evening Shadows',2.5);
INSERT INTO mytable(Tittle,Rating) VALUES ('706',1.8);
INSERT INTO mytable(Tittle,Rating) VALUES ('Falsafa: The Other Side',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('A Thin Line',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Battalion 609',1.7);
INSERT INTO mytable(Tittle,Rating) VALUES ('The Accidental Prime Minister',3.6);
INSERT INTO mytable(Tittle,Rating) VALUES ('URI: The Surgical Strike',4.7);
INSERT INTO mytable(Tittle,Rating) VALUES ('Salt Bridge',2.9);
INSERT INTO mytable(Tittle,Rating) VALUES ('Dharma Bhai',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('Kanpur Ke Sholay',NULL);
INSERT INTO mytable(Tittle,Rating) VALUES ('English Ki Taay Taay Fisss',NULL);
